### PR TITLE
Update TextBlock.pm

### PR DESCRIPTION
**Pull request by filipecustodio**
This fixes the center and right alignment for paragraphs with tags.

### CODE REVIEW

**Comment by jhannah** [comment]
oh ... I was going to merge this today? But you closed it? So you don't want this code in master?

**Comment by filipecustodio** [comment]
Dear Jay,

Sorry… I have 0 experience with pull requests, I thought I had to close it so you could do the merge.

It's now reopened, sorry for the confusion.

Cheers,

**Comment by jhannah** [comment]
Oh, no worries. I haven't touched this module in YEARS. :) Anyway, I tried your patch and it didn't seem to fix the problem for me. Did it seem to fix the problem for you? I tried to clean up and describe the problem, as I understand it, over in #4. Does that description of the bug match the bug you're trying to fix? Thanks!

**Comment by jhannah** [comment]
Incidentally, I pushed versions 0.09 and 0.10 to CPAN today.

**Comment by filipecustodio** [comment]
> Oh, no worries. I haven't touched this module in YEARS. :) Anyway, I tried your patch and it didn't seem to fix the problem for me. Did it seem to fix the problem for you? I tried to clean up and describe the problem, as I understand it, over in #4. Does that description of the bug match the bug you're trying to fix? Thanks!

Dear Jay, my fix did not make onto the final code, probably because I botched the pull request. I'm going to retry it.

Cheers!

**Comment by filipecustodio** [comment]
Closing this and opening a new one for version 1.0.

**Pull request closed without merging**
